on:
  push:
    branches: [master]

name: release-please
jobs:
  release-please:
    name: "Release please"
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: kurtosis
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          # Our CI, Docker Images, Kurtosis-SDK bumps all depend on
          # non v tags
          include-v-in-tag: false
          changelog-types: >-
            [
              {"type":"feat",     "section":"Features",              "hidden":false},
              {"type":"fix",      "section":"Bug Fixes",             "hidden":false},
              {"type":"refactor", "section":"Refactors",             "hidden":false},
              {"type":"docs",     "section":"Documentation Updates", "hidden":false},
              {"type":"ci",       "section":"Miscellaneous",         "hidden":false},
              {"type":"build",    "section":"Miscellaneous",         "hidden":false},
              {"type":"test",     "section":"Miscellaneous",         "hidden":false},
              {"type":"chore",    "section":"Miscellaneous",         "hidden":false}
            ]
